# Generated by Django 5.2.13 on 2026-04-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
